# Generated by Django 5.0.4 on 2024-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_artifact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='is_magic',
            new_name='is_magical',
        ),
    ]
