# Generated by Django 5.0.4 on 2024-06-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
