# Generated by Django 5.0.4 on 2024-06-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_last_edited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_edited_on',
        ),
    ]
